language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.6.2
      script:
        - bundle exec danger
    - rvm: 2.6.2
      env: DATABASE_ADAPTER=activerecord
      services:
        - postgresql
    - rvm: 2.6.2
      env: DATABASE_ADAPTER=mongoid
      services:
        - mongodb
